# Generated by Django 5.2.9 on 2026-01-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
