# Generated by Django 5.2.9 on 2025-12-21 07:40

import common.helpers.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomg', '0002_fileitem_user_fileitemconnector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file',
            field=models.FileField(upload_to=common.helpers.media_paths.get_media_path_prefix),
        ),
    ]
